from .add_url import AddUrlDialog
from .file_info import DownloadFileInfoDialog
from .options import OptionsDialog
from .properties import PropertiesDialog
from .progress import DownloadProgressDialog
from .complete import DownloadCompleteDialog
from .column import ColumnDialog
from .delete import DeleteDialog
from .refresh import RefreshAddressDialog
from .rename import RenameDialog
from .media_downloader import MediaDownloaderDialog
from .scheduler import SchedulerDialog
from .duplicate import DuplicateDownloadDialog
