name: 'Build Extension'
description: 'Builds Chrome (.crx) and Firefox (.xpi) browser extension packages'

runs:
  using: "composite"
  steps:
    - name: Build Extension Packages
      shell: bash
      run: |
        python scripts/pack_extension.py extension_build
        cp extension_build/bengal-download-manager-extension.crx extension-chromium.crx
        cp extension_build/bengal-download-manager-firefox.xpi extension-firefox.xpi
        rm -rf extension_build
